server:
  port: 9002

spring:
  data:
    mongodb:
      uri: mongodb+srv://abhisreekrishna742_db_user:OtepNhURCnqp9RDD@algoverse.a1ylkpx.mongodb.net/
      database: Algoverse

app:
  issuer: http://localhost:9002
